# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 21:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('dead_line', models.DateField()),
                ('create_date', models.DateTimeField(default=datetime.datetime(2016, 8, 24, 21, 12, 44, 625132))),
                ('slug', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
