# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=10)),
                ('create_date', models.DateField(default=datetime.date.today)),
                ('slug', models.CharField(max_length=50)),
            ],
        ),
    ]
