# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20160819_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
